name: esports
description: "A new Flutter project."

publish_to: 'none' # Prevent accidental publishing to pub.dev.

version: 1.0.0+1

environment:
  sdk: '>=3.4.4 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  # CupertinoIcons for iOS style icons.
  cupertino_icons: ^1.0.6

  # Firebase Core for integrating Firebase services.
  firebase_core: ^3.8.0

  # Add other dependencies such as Firebase Authentication or Firestore if needed.
  # firebase_auth: ^4.0.0
  # cloud_firestore: ^5.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  # Recommended linting package for Flutter projects.
  flutter_lints: ^3.0.0

flutter:
  # Material design components (essential for many Flutter apps).
  uses-material-design: true

  # Assets section where you can define your image assets and other resources.
  assets:
    - assets/images/

  # Additional assets may be added here for other resources like fonts, audio files, etc.

  # To add custom fonts to your application, add a fonts section:
  # fonts:
  #   - family: Roboto
  #     fonts:
  #       - asset: fonts/Roboto-Regular.ttf
  #       - asset: fonts/Roboto-Bold.ttf
  #         weight: 700
  #   - family: Arial
  #     fonts:
  #       - asset: fonts/Arial-Regular.ttf
  #       - asset: fonts/Arial-Bold.ttf
  #         weight: 700
