// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBb80jaHz-5XeKUMHjHDbSD7wJ1QAgvid0',
    appId: '1:379506167391:web:842ede01f8e3d7eb9255ea',
    messagingSenderId: '379506167391',
    projectId: 'blog-app-f8e97',
    authDomain: 'blog-app-f8e97.firebaseapp.com',
    storageBucket: 'blog-app-f8e97.firebasestorage.app',
    measurementId: 'G-CC4CSYWRXC',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAJIsyHJskXphXdrmh5OTYXfpbYVWSh_s8',
    appId: '1:379506167391:android:293fd3783e8e9c3f9255ea',
    messagingSenderId: '379506167391',
    projectId: 'blog-app-f8e97',
    storageBucket: 'blog-app-f8e97.firebasestorage.app',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBb80jaHz-5XeKUMHjHDbSD7wJ1QAgvid0',
    appId: '1:379506167391:web:9d126e23b8fe3bbb9255ea',
    messagingSenderId: '379506167391',
    projectId: 'blog-app-f8e97',
    authDomain: 'blog-app-f8e97.firebaseapp.com',
    storageBucket: 'blog-app-f8e97.firebasestorage.app',
    measurementId: 'G-DRLG8T1V5E',
  );

}